import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

interface PerformanceData {
  topics: Array<{
    name: string
    accuracy: number
    timeSpent: number
    questionsAttempted: number
    questionsCorrect: number
  }>
  overallAccuracy: number
  totalTime: number
  testDuration: number
  testTitle: string
  studentLevel?: string
}

interface AIInsight {
  strengths: string[]
  weaknesses: string[]
  recommendations: string[]
  studyPlan: string[]
  motivationalMessage: string
  nextSteps: string[]
}

serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response('ok', {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST',
        'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
      },
    })
  }

  try {
    console.log('🚀 AI Insights function called')
    
    const requestBody = await req.json()
    console.log('📥 Request body:', JSON.stringify(requestBody, null, 2))
    
    const { performanceData }: { performanceData: PerformanceData } = requestBody

    if (!performanceData || !performanceData.topics) {
      console.error('❌ Invalid performance data provided')
      throw new Error('Invalid performance data provided')
    }

    console.log('📊 Performance data received:', performanceData)

    // Get Gemini API key from environment
    const geminiApiKey = Deno.env.get('GEMINI_API_KEY')
    if (!geminiApiKey) {
      console.error('❌ Gemini API key not configured')
      console.log('🔄 Using fallback insights instead')
      
      // Return fallback insights if no API key
      const fallbackInsights = generateFallbackInsights(performanceData)
      return new Response(JSON.stringify({ 
        insights: fallbackInsights,
        fallback: true,
        message: 'Using fallback insights - Gemini API key not configured'
      }), {
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      })
    }

    console.log('🤖 Generating AI insights with Gemini...')
    
    // Generate AI insights using Gemini
    const insights = await generateGeminiInsights(performanceData, geminiApiKey)
    
    console.log('✅ AI insights generated successfully')

    return new Response(JSON.stringify({ insights }), {
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
    })
  } catch (error) {
    console.error('❌ Error in AI insights function:', error)
    
    try {
      // Try to get performance data for fallback
      const requestBody = await req.json()
      const fallbackInsights = generateFallbackInsights(requestBody.performanceData)
      
      return new Response(JSON.stringify({ 
        insights: fallbackInsights,
        fallback: true,
        error: error.message 
      }), {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      })
    } catch (fallbackError) {
      console.error('❌ Fallback also failed:', fallbackError)
      
      return new Response(JSON.stringify({ 
        error: 'Failed to generate insights',
        details: error.message 
      }), {
        status: 500,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      })
    }
  }
})

async function generateGeminiInsights(data: PerformanceData, apiKey: string): Promise<AIInsight> {
  const prompt = buildGeminiPrompt(data)
  
  console.log('📝 Sending prompt to Gemini:', prompt.substring(0, 200) + '...')
  
  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${apiKey}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [{
        parts: [{
          text: prompt
        }]
      }],
      generationConfig: {
        temperature: 0.7,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 1024,
      }
    })
  })

  if (!response.ok) {
    const errorText = await response.text()
    console.error('❌ Gemini API error:', response.status, errorText)
    throw new Error(`Gemini API error: ${response.status} - ${errorText}`)
  }

  const result = await response.json()
  console.log('📡 Gemini response:', JSON.stringify(result, null, 2))
  
  const generatedText = result.candidates?.[0]?.content?.parts?.[0]?.text
  
  if (!generatedText) {
    console.error('❌ No content generated by Gemini')
    throw new Error('No content generated by Gemini')
  }

  console.log('📄 Generated text:', generatedText)
  
  return parseGeminiResponse(generatedText)
}

function buildGeminiPrompt(data: PerformanceData): string {
  const topicPerformance = data.topics.map(topic => 
    `${topic.name}: ${topic.accuracy.toFixed(1)}% accuracy (${topic.questionsCorrect}/${topic.questionsAttempted} correct)`
  ).join('\n')

  const timeEfficiency = ((data.totalTime / data.testDuration) * 100).toFixed(1)

  return `
You are an expert educational AI tutor. Analyze this student's test performance and provide personalized, actionable insights.

**Test Performance Analysis:**

Test: ${data.testTitle}
Overall Accuracy: ${data.overallAccuracy.toFixed(1)}%
Time Efficiency: ${timeEfficiency}% of allocated time used
Student Level: ${data.studentLevel || 'intermediate'}

**Topic-wise Breakdown:**
${topicPerformance}

**Please provide a JSON response with exactly these keys:**

{
  "strengths": ["2-3 specific strengths based on the data"],
  "weaknesses": ["2-3 areas that need improvement"],
  "recommendations": ["3-4 specific, actionable study recommendations"],
  "studyPlan": ["3-4 concrete steps for a personalized study plan"],
  "motivationalMessage": "An encouraging, personalized message (1-2 sentences)",
  "nextSteps": ["2-3 immediate actions the student should take"]
}

**Guidelines:**
- Be specific and reference actual performance data
- Focus on actionable advice, not generic tips
- Be encouraging while being honest about areas for improvement
- Tailor recommendations to the student's current level
- Include time management advice if relevant

Respond ONLY with valid JSON, no additional text.
  `.trim()
}

function parseGeminiResponse(response: string): AIInsight {
  try {
    console.log('🔍 Parsing Gemini response...')
    
    // Clean the response to extract JSON
    const jsonMatch = response.match(/\{[\s\S]*\}/)
    if (!jsonMatch) {
      console.error('❌ No JSON found in response')
      throw new Error('No JSON found in response')
    }
    
    const cleanedResponse = jsonMatch[0]
      .replace(/```json/g, '')
      .replace(/```/g, '')
      .trim()
    
    console.log('🧹 Cleaned response:', cleanedResponse)
    
    const parsed = JSON.parse(cleanedResponse)
    
    // Validate required fields
    const required = ['strengths', 'weaknesses', 'recommendations', 'studyPlan', 'motivationalMessage', 'nextSteps']
    for (const field of required) {
      if (!parsed[field]) {
        console.error(`❌ Missing required field: ${field}`)
        throw new Error(`Missing required field: ${field}`)
      }
    }
    
    console.log('✅ Successfully parsed AI response')
    return parsed as AIInsight
  } catch (error) {
    console.error('❌ Failed to parse Gemini response:', error)
    console.error('Raw response:', response)
    throw new Error(`Failed to parse AI response: ${error.message}`)
  }
}

function generateFallbackInsights(data: PerformanceData): AIInsight {
  console.log('🔄 Generating fallback insights')
  
  if (!data || !data.topics || data.topics.length === 0) {
    return {
      strengths: ["Completed the test successfully", "Showed persistence in attempting questions"],
      weaknesses: ["Need more practice with various question types", "Focus on building foundational concepts"],
      recommendations: ["Review basic concepts", "Practice regularly", "Analyze mistakes carefully"],
      studyPlan: ["Set aside 30 minutes daily for practice", "Focus on one topic at a time", "Track your progress weekly"],
      motivationalMessage: "Every expert was once a beginner. Keep practicing and you'll see improvement!",
      nextSteps: ["Identify your weakest topic", "Find additional practice resources", "Set a study schedule"]
    }
  }

  const bestTopic = data.topics.reduce((max, topic) => 
    topic.accuracy > max.accuracy ? topic : max
  )
  const worstTopic = data.topics.reduce((min, topic) => 
    topic.accuracy < min.accuracy ? topic : min
  )
  
  const timeEfficiency = (data.totalTime / data.testDuration) * 100
  const isSlowPaced = timeEfficiency > 85
  const isFastPaced = timeEfficiency < 60

  return {
    strengths: [
      `Strong performance in ${bestTopic.name} (${bestTopic.accuracy.toFixed(1)}% accuracy)`,
      data.overallAccuracy > 70 ? "Good conceptual understanding" : "Consistent effort across all topics",
      isFastPaced ? "Efficient time management" : "Thoughtful approach to questions"
    ].slice(0, 3),
    
    weaknesses: [
      `Need improvement in ${worstTopic.name} (${worstTopic.accuracy.toFixed(1)}% accuracy)`,
      isSlowPaced ? "Time management needs attention" : "Focus on accuracy over speed",
      data.overallAccuracy < 50 ? "Fundamental concepts need strengthening" : "Minor gaps in advanced topics"
    ].slice(0, 3),
    
    recommendations: [
      `Dedicate extra time to practicing ${worstTopic.name} problems`,
      "Review incorrect answers to understand mistake patterns",
      isSlowPaced ? "Practice timed exercises to improve speed" : "Focus on accuracy before increasing speed",
      "Use spaced repetition for better retention"
    ],
    
    studyPlan: [
      `Spend 40% of study time on ${worstTopic.name}`,
      `Maintain strength in ${bestTopic.name} with regular practice`,
      "Take weekly practice tests to track improvement",
      "Review and analyze mistakes after each practice session"
    ],
    
    motivationalMessage: data.overallAccuracy > 60 
      ? "You're on the right track! Focus on your weak areas and you'll see great improvement."
      : "Every mistake is a learning opportunity. Stay consistent with your practice and success will follow!",
    
    nextSteps: [
      `Start with 15 minutes of ${worstTopic.name} practice daily`,
      "Create a study schedule and stick to it",
      "Find additional resources for your challenging topics"
    ]
  }
}
